#! /bin/bash

# 00_how_to_docker - 02
# Q: Récupérer l’adresse IP de la machine virtuelle 'Char'

set -o xtrace -o errexit

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    VBoxManage guestproperty enumerate Char | grep IP
	exit 1
fi

docker-machine ip Char

# Sources:
# https://docs.docker.com/machine/reference/ip/
