#! /bin/bash

# 00_how_to_docker - 02
# Q: Récupérer l’adresse IP de la machine virtuelle 'Char'

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	    (set -x; VBoxManage guestproperty enumerate Char | grep IP)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker-machine ip Char

# Sources:
# https://docs.docker.com/machine/reference/ip/
