#! /bin/bash

# 00_how_to_docker - 03
# Q: Assigner les variables spécifiques à la machine virtuelle 'Char' dans l’env
#    courant de votre terminal, de sorte que vous pouvez lancer la commande 
#    'docker ps' sans erreurs.
#    Une seule commande est attendue pour fixer les 4 variables d’environnement
#    et il vous est interdit d’utiliser le builtin de votre shell pour set à la
#    main ces variables.

VM_NAME="Char"

set -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
    (set -x; eval $(docker-machine env --unset))
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    (set -x; env | grep DOCKER)
	exit 1
fi

(set -x; eval "$(docker-machine env $VM_NAME)")
exec $SHELL -i

# Sources:
# https://docs.docker.com/machine/reference/env/
# unset: `eval $(docker-machine env --unset)`