#! /bin/bash

# 00_how_to_docker - 04
# Q: Récupérer depuis le Docker Hub le container 'hello-world' disponible sur le
#    Docker Hub.

IMG="hello-world"

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	echo "$ docker image rm $IMG --force"
	docker image rm $IMG --force
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    echo "$ docker image ls"
    docker image ls
	exit 1
fi

echo "$ docker pull $IMG"
docker pull $IMG

# Sources:
# https://docs.docker.com/engine/reference/commandline/pull/