#! /bin/bash

# 00_how_to_docker - 04
# Q: Récupérer depuis le Docker Hub le container 'hello-world' disponible sur le
#    Docker Hub.

IMG="hello-world"

set -o xtrace -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	docker image rm $IMG --force
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    docker image ls
	exit 1
fi

docker pull $IMG

# Sources:
# https://docs.docker.com/engine/reference/commandline/pull/