#! /bin/bash

# 00_how_to_docker - 05
# Q: Lancer le container 'hello-world' et faire en sorte que le container
#    affiche bien son message d’accueil, puis le quitte.

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0}"
    echo "Use your eyes 👀"
	exit 1
fi

set -o xtrace
docker run hello-world

# Sources:
# https://docs.docker.com/get-started/#test-docker-version