#! /bin/bash

# 00_how_to_docker - 06
# Q: Lancer un container 'nginx' disponible sur le Docker Hub en tâche de fond.
#    Le container lancé doit avoir pour nom 'overlord', doit pouvoir redémarrer
#    de lui-même et doit avoir le port 80 du container rattaché au port 5000 de
#    'Char'. Vous pouvez vérifier le fonctionnement de votre container en allant
#    sur un 'http://<ip-de-char>:5000' comme URL sur votre navigateur internet.

OS=`uname`
VM="Char"
IP=$(docker-machine ip $VM)
NAME_CONT="overlord"
PORT_VM=5000
PORT_CONT=80
URL="http://"$IP":"$PORT_VM
if [ "$OS" = 'Linux' ]; then OPEN="xdg-open" ; else OPEN="open"; fi

set -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	(set -x; docker stop $NAME_CONT && docker container rm $NAME_CONT)
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    (set -x; docker ps -a | grep "overlord\|NAMES")
	echo && read -p "open [oO] or curl [cC] $URL ? " -n 1 -r
	if [[ $REPLY =~ ^[cC]$ ]]; then
		(set -x; curl $URL)
	elif [[ $REPLY =~ ^[oO]$ ]]; then
		(set -x; $OPEN $URL)
	fi
	exit 1
fi

set -o xtrace
docker run -d \
	--name=$NAME_CONT \
	-p $PORT_VM:$PORT_CONT \
	--restart always \
	nginx

# Sources:
# https://docs.docker.com/engine/reference/commandline/run/
# -d=false: Detached mode: Run container in the background, print new container id
# --publish , -p		Publish a container’s port(s) to the host
# --restart	no|on-failure|always	Restart policy to apply when a container exits