#! /bin/bash

# 00_how_to_docker - 07
# Q: Récupérer l’adresse IP interne du container 'overlord' sans lancer son
#    shell et en une commande.

CONTAINER_ID=overlord

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	    (set -x; docker inspect $CONTAINER_ID | grep IP)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $CONTAINER_ID 

# Sources:
# https://stackoverflow.com/questions/17157721/how-to-get-a-docker-containers-ip-address-from-the-host