#! /bin/bash

# 00_how_to_docker - 08
# Q: Lancer un shell depuis un container 'alpine', en faisant en sorte que vous
#    puissiez directement interagir avec le container via votre terminal et que
#	 le container se supprime à la fin de l’exécution du shell.

set -o xtrace -o errexit

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    docker ps -a
	exit 1
fi

docker run -it --rm alpine

# Sources:
# https://docs.docker.com/engine/reference/commandline/run/
# --rm	Automatically remove the container when it exits (docker run --help)
# -i	Interactive mode (Keep STDIN open even if not attached)
# -t	Allocate a pseudo-TTY
#
# Delete all containers : 	`docker rm $(docker ps -a -q)`
# Delete all images : 		`docker rmi $(docker images -q)`