#! /bin/bash

# 00_how_to_docker - 11
# Q: Lister les volumes Docker crées sur la machine... je dis bien VOLUMES

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0} [OPTION]"
	exit 1
fi

set -o xtrace
docker volume ls --filter driver=local

# Sources:
# Storage: https://docs.docker.com/storage/
# Volumes: https://docs.docker.com/storage/volumes/
# docker volume --help