#! /bin/bash

# 00_how_to_docker - 12
# Q: Lancer un container 'mysql' en tâche de fond. Il devra aussi pouvoir
#    redémarrer de lui-même en cas d’erreur et faire en sorte que le password
#    root de la base de données soit 'Kerrigan'. Vous ferez aussi en sorte que
#    la base de données soit stockée dans le volume 'hatchery', que le container
#    crée directement une base de données qui aura comme nom 'zerglings' et le
#    container s’appellera 'spawning-pool'.

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    echo "docker ps -a"
	docker ps -a
	echo
	echo "docker inspect --format '{{json .Mounts}}' spawning-pool | sed \"s/,/\n/g\" | tr -d \"[{}]\""
	docker inspect --format '{{json .Mounts}}' spawning-pool | sed "s/,/\n/g" | tr -d "[{}]"
	echo
	echo "docker exec -it spawning-pool /bin/sh -c 'find / -name \"zerglings\" 2>/dev/null; exit \$?'"
	docker exec -it spawning-pool /bin/sh -c 'find / -name "zerglings" 2>/dev/null; exit $?'
	exit 1
fi

echo docker run -d --name spawning-pool \
		--mount 'type=volume,src=hatchery,dst=/var/lib/mysql' \
		--env MYSQL_DATABASE=zerglings \
		--env MYSQL_ROOT_PASSWORD=Kerrigan \
		--restart on-failure \
		mysql

docker run -d --name spawning-pool \
		--mount 'type=volume,src=hatchery,dst=/var/lib/mysql' \
		--env MYSQL_DATABASE=zerglings \
		--env MYSQL_ROOT_PASSWORD=Kerrigan \
		--restart on-failure \
		mysql

# Sources:
# https://docs.docker.com/engine/reference/commandline/run/
# -d=false: Detached mode: Run container in the background, print new container id
# --publish , -p		Publish a container’s port(s) to the host
# --restart	no|on-failure|always	Restart policy to apply when a container exits