#! /bin/bash

# 00_how_to_docker - 12
# Q: Lancer un container 'mysql' en tâche de fond. Il devra aussi pouvoir
#    redémarrer de lui-même en cas d’erreur et faire en sorte que le password
#    root de la base de données soit 'Kerrigan'. Vous ferez aussi en sorte que
#    la base de données soit stockée dans le volume 'hatchery', que le container
#    crée directement une base de données qui aura comme nom 'zerglings' et le
#    container s’appellera 'spawning-pool'.

NAME_CONT="spawning-pool"
NETWORK_NAME="sql_network"

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
		(set -x; docker stop $NAME_CONT && docker container rm $NAME_CONT)
	elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
		(set -x; docker ps -a)
		echo
		(set -x; docker inspect --format '{{json .Mounts}}' spawning-pool | tr ',' '\n' | tr -d "[{}]")
		echo
		(set -x; docker exec -it spawning-pool /bin/sh -c 'find / -name "zerglings" 2>/dev/null; exit $?')
		echo
		(set -x; docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' spawning-pool | grep MYSQL)
	else
		echo Usage: "${0} [OPTION]"
		echo "-u   --undo"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker run -dit \
		--name $NAME_CONT \
		--mount 'type=volume,src=hatchery,dst=/var/lib/mysql' \
		--env MYSQL_DATABASE=zerglings \
		--env MYSQL_ROOT_PASSWORD=Kerrigan \
		--restart on-failure \
		mysql:5.7

# Sources:
# https://docs.docker.com/engine/reference/commandline/run/
# https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag
# https://hub.docker.com/_/mysql/