#! /bin/bash

# 00_how_to_docker - 13
# Q: Afficher les variables d’environnement du container 'spawning-pool' en une
#    seule commande, histoire d’être sûr que vous avez bien configuré votre
#	 container.

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	echo "$ docker exec -it spawning-pool /bin/sh -c 'env; exit \$?'"
	docker exec -it spawning-pool /bin/sh -c 'env; exit $?'
	exit 1
fi

echo "$ docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' spawning-pool"
docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' spawning-pool

# Sources:
# https://docs.docker.com/engine/reference/commandline/inspect/
# https://stackoverflow.com/a/30343218