#! /bin/bash

# 00_how_to_docker - 13
# Q: Afficher les variables d’environnement du container 'spawning-pool' en une
#    seule commande, histoire d’être sûr que vous avez bien configuré votre
#	 container.

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
		(set -x; docker exec -it spawning-pool /bin/sh -c 'env; exit $?')
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker inspect --format='{{range .Config.Env}}{{println .}}{{end}}' spawning-pool

# Sources:
# https://docs.docker.com/engine/reference/commandline/inspect/
# https://stackoverflow.com/a/30343218