#! /bin/bash

# 00_how_to_docker - 14
# Q: Lancer un container 'wordpress' en tâche de fond.
#    Le container doit avoir pour nom 'lair', le port 80 du container doit etre
#	 bindé au port 8080 de la machine virtuelle et doit pouvoir utiliser le
#	 container 'spawning-pool' comme service de base de données.
#	 Vous pouvez tenter d’accéder à 'lair' sur votre machine via un navigateur
#	 en rentrant l’adresse IP de la machine virtuelle comme URL.
#	 Bravo, vous venez de deployer un site Wordpress fonctionnel en 2 commandes!

OS=`uname`
VM="Char"
IP=$(docker-machine ip $VM)
NAME_CONT="lair"
PORT_VM=8080
PORT_CONT=80
URL="http://"$IP":"$PORT_VM
if [ "$OS" = 'Linux' ]; then OPEN="xdg-open" ; else OPEN="open"; fi

set -o xtrace -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	echo "$ docker stop $NAME_CONT && docker container rm $NAME_CONT"
	docker stop $NAME_CONT && docker container rm $NAME_CONT
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    echo "$ docker ps -a"
    docker ps -a   
	echo
	read -p "open [oO] or curl [cC] $URL ? " -n 1 -r
	if [[ $REPLY =~ ^[oOyY]$ ]]; then
		printf "\nopen %s\n" $URL
		$OPEN $URL
	elif [[ $REPLY =~ ^[cC]$ ]]; then
		printf "\ncurl %s\n" $URL
		curl $URL
	fi
	exit 1
fi

echo $ docker run -d \
		--name $NAME_CONT \
		--link spawning-pool:mysql \
		-p $PORT_VM:$PORT_CONT \
		wordpress

docker run -d \
		--name $NAME_CONT \
		--link spawning-pool:mysql \
		-p $PORT_VM:$PORT_CONT \
		wordpress

# Sources:
# https://docs.docker.com/engine/reference/run/
# https://docs.docker.com/engine/reference/commandline/run/
# https://docs.docker.com/samples/library/wordpress/