#! /bin/bash

# 00_how_to_docker - 15
# Q: Lancer un container 'phpmyadmin' en tâche de fond. Le container doit avoir
#    pour nom 'roach-warden', le port 80 du container doit etre bindé au port
#    8081 de la machine virtuelle et doit pouvoir faire en sorte d’aller
#    explorer la base de données contenue dans le container 'spawning-pool'.

OS=`uname`
VM="Char"
IP=$(docker-machine ip $VM)
NAME_CONT="roach-warden"
PORT_VM=8081
PORT_CONT=80
URL="http://"$IP":"$PORT_VM
if [ "$OS" = 'Linux' ]; then OPEN="xdg-open" ; else OPEN="open"; fi

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
		(set -x; docker stop $NAME_CONT && docker container rm $NAME_CONT)
	elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	    (set -x; docker ps -a)
		echo && read -p "open [oO] or curl [cC] $URL ? " -n 1 -r
		if [[ $REPLY =~ ^[oO]$ ]]; then
			(set -x; $OPEN $URL)
		elif [[ $REPLY =~ ^[cC]$ ]]; then
			(set -x; curl $URL)
		fi
	else
		echo Usage: "${0} [OPTION]"
		echo "-u   --undo"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker run -d \
		--name $NAME_CONT \
		--link spawning-pool:db \
		-p $PORT_VM:$PORT_CONT \
		phpmyadmin/phpmyadmin

# Sources:
# https://docs.docker.com/engine/reference/run/
# https://docs.docker.com/engine/reference/commandline/run/
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/