#! /bin/bash

# 00_how_to_docker - 15
# Q: Lancer un container 'phpmyadmin' en tâche de fond. Le container doit avoir
#    pour nom 'roach-warden', le port 80 du container doit etre bindé au port
#    8081 de la machine virtuelle et doit pouvoir faire en sorte d’aller
#    explorer la base de données contenue dans le container 'spawning-pool'.

OS=`uname`
VM="Char"
IP=$(docker-machine ip $VM)
NAME_CONT="roach-warden"
PORT_VM=8081
PORT_CONT=80
URL="http://"$IP":"$PORT_VM
if [ "$OS" = 'Linux' ]; then OPEN="xdg-open" ; else OPEN="open"; fi

set -o xtrace -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	echo "$ docker stop $NAME_CONT && docker container rm $NAME_CONT"
	docker stop $NAME_CONT && docker container rm $NAME_CONT
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    echo "$ docker ps -a"
    docker ps -a   
	echo
	read -p "open [oO] or curl [cC] $URL ? " -n 1 -r
	if [[ $REPLY =~ ^[oO]$ ]]; then
		printf "\nopen %s\n" $URL
		$OPEN $URL
	elif [[ $REPLY =~ ^[cC]$ ]]; then
		printf "\ncurl %s\n" $URL
		curl $URL
	fi
	exit 1
fi

echo $ docker run -d \
		--name $NAME_CONT \
		--link spawning-pool:db \
		-p $PORT_VM:$PORT_CONT \
		phpmyadmin/phpmyadmin

docker run -d \
		--name $NAME_CONT \
		--link spawning-pool:db \
		-p $PORT_VM:$PORT_CONT \
		phpmyadmin/phpmyadmin

#		--link spawning-pool:db \
# Sources:
# https://docs.docker.com/engine/reference/run/
# https://docs.docker.com/engine/reference/commandline/run/
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/