#! /bin/bash

# 00_how_to_docker - 16
# Q: Consulter les logs en temps réel du container 'spawning-pool' sans executer
#    son shell pour autant.

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0} [OPTION]"
    echo "Use your eyes 👀"
	exit 1
fi

set -o xtrace
docker logs --follow spawning-pool

# Sources:
# https://docs.docker.com/engine/reference/commandline/logs/