#! /bin/bash

# 00_how_to_docker - 17
# Q: Afficher l’ensemble des containers actuellement actifs sur la machine
#    virtuelle 'Char'.

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0} [OPTION]"
    echo "Use your eyes 👀"
	exit 1
fi

set -o xtrace
docker ps

# Sources:
# https://docs.docker.com/engine/reference/commandline/ps/