#! /bin/bash

# 00_how_to_docker - 18
# Q: Relancer le container overlord

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
		(set -x; docker ps)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker container restart overlord

# Sources:
# docker container --help