#! /bin/bash

# 00_how_to_docker - 18
# Q: Relancer le container overlord

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
    echo "$ docker ps" 
	docker ps
	exit 1
fi

echo "$ docker container restart overlord"
docker container restart overlord

# Sources:
# docker container --help