#! /bin/bash

# 00_how_to_docker - 18
# Q: Relancer le container overlord

set -o errexit

if [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	(set -x; docker ps)
	exit 1
fi

set -o xtrace
docker container restart overlord

# Sources:
# docker container --help