#! /bin/bash

# 00_how_to_docker - 20
# Q: Créer un 'swarm' local où la machine virtuelle 'Char' en est le manager.

VM="Char"
IP=$(docker-machine ip $VM)

set -o xtrace -o errexit

if [ "${1}" = "-u" ] || [ "${1}" = "--undo" ]; then
	docker-machine ssh $VM "docker swarm leave --force"
	exit 1
elif [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
	docker-machine ssh $VM "docker node ls"
	exit 1
fi

docker-machine ssh $VM "docker swarm init --advertise-addr $IP"

# Sources:
# https://docs.docker.com/get-started/part4/