#! /bin/bash

# 00_how_to_docker - 20
# Q: Créer un 'swarm' local où la machine virtuelle 'Char' en est le manager.

VM="Char"
IP=$(docker-machine ip $VM)

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-u" ] || [ "${1}" = "--undo" ]; then
		(set -x; docker-machine ssh $VM "docker swarm leave --force")
		exit 1
	elif [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; docker-machine ssh $VM "docker node ls")
	else
		echo Usage: "${0} [OPTION]"
		echo "-u   --undo"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker-machine ssh $VM "docker swarm init --advertise-addr $IP"

# Sources:
# https://docs.docker.com/get-started/part4/