#! /bin/bash

# 00_how_to_docker - 21
# Q: Créer une autre machine virtuelle avec 'docker-machine' utilisant le driver
#    'virtualbox' et ayant pour nom 'Aiur'

VM_NAME="Aiur"

set -o errexit

if [ "$1" = "-u" ] || [ "$1" = "--undo" ]; then
	(set -x; docker-machine stop $VM_NAME && docker-machine rm $VM_NAME)
	exit 1
elif [ "$1" = "-c" ] || [ "$1" = "--check" ]; then
	(set -x; docker-machine ls)
	exit 1
fi

set -o xtrace
docker-machine create --driver virtualbox $VM_NAME

# Sources:
# https://docs.docker.com/machine/reference/create/
# List all available virtual machines: 			`VBoxManage list vms`
# List all running available virtual machines:	`VBoxManage list runningvms`
