#! /bin/bash

# 00_how_to_docker - 22
# Q: Basculer 'Aiur' comme esclave du swarm local où 'Char' est leader
#    (La commande de prise de contrôle de 'Aiur' n’est pas demandée).

SWARM_AGENT_MASTER="Char"
SWARM_AGENT_SLAVE="Aiur"
IP_MANAGER=$(docker-machine ip $SWARM_AGENT_MASTER)
MANAGER_TOKEN=$(docker-machine ssh $SWARM_AGENT_MASTER "docker swarm join-token manager -q")
WORKER_TOKEN=$(docker-machine ssh $SWARM_AGENT_MASTER "docker swarm join-token worker -q")

set -o errexit

if [ "${1}" = "-u" ] || [ "${1}" = "--undo" ]; then
	(set -x; docker-machine ssh $SWARM_AGENT_SLAVE "docker swarm leave --force")
	(set -x; docker-machine ssh $SWARM_AGENT_MASTER "docker node rm --force $SWARM_AGENT_SLAVE")
	exit 1
elif [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
	(set -x; docker-machine ssh $SWARM_AGENT_MASTER "docker node ls")
	exit 1
fi

set -o xtrace
docker-machine ssh $SWARM_AGENT_SLAVE \
	"docker swarm join --token $WORKER_TOKEN $IP_MANAGER:2377"

# Sources:
# https://docs.docker.com/get-started/part4/
# https://docs.docker.com/engine/reference/commandline/swarm_join-token/
# https://docs.docker.com/engine/reference/commandline/swarm_leave/
# https://docs.docker.com/engine/reference/commandline/node_rm/