#! /bin/bash

# 00_how_to_docker - 25
# Q: Lister l’ensemble des services du swarm local

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0}"
	exit 1
fi

(set -x; docker service ls)

# Sources:
# https://docs.docker.com/get-started/part3/
# https://docs.docker.com/engine/reference/commandline/service_create/
# https://hub.docker.com/_/rabbitmq/
# Sources
# https://docs.docker.com/engine/reference/commandline/service_ls/