#! /bin/bash

# 00_how_to_docker - 26
# Q: Lancer un service '42school/engineering-bay' en 2 répliques et faire en
#    sorte que le service fonctionne (se référer à la doc fournie dans 'hub.docker.com'). 
#    Ce service s’appellera 'engineering-bay' et sera sur le reseau 'overmind'

