#! /bin/bash

# 00_how_to_docker - 27
# Q: Récuperer les logs en continu d’une des tasks du service 'engineering-bay'

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-u" ] || [ "${1}" = "--undo" ]; then
		(set -x; )
	elif [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; )
	else
		echo Usage: "${0} [OPTION]"
		echo "-u   --undo"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace


# Sources:
#
