#! /bin/bash

# 00_how_to_docker - 27
# Q: Récuperer les logs en continu d’une des tasks du service 'engineering-bay'

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0}"
	exit 1
fi

set -o xtrace
docker service logs --follow engineering-bay

# Sources:
# docker service --help
# docker service logs --help
