#! /bin/bash

# 00_how_to_docker - 28
# Q: .. Damn, des zergs sont en train d’attaquer 'orbital-command' et couper le
#    service 'engineering-bay' ne servira a rien... Vous devez envoyer des Marines
#	 pour les éliminer...
#	 Lancer un service '42school/marine-squad' en 2 repliques, et faites en sorte
#	 que le service fonctionne (se référer à la doc fournie dans hub.docker.com)
#	 Ce service s’appellera ... 'marines' et sera sur le 'reseau overmind'

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-u" ] || [ "${1}" = "--undo" ]; then
		(set -x; )
	elif [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; )
	else
		echo Usage: "${0} [OPTION]"
		echo "-u   --undo"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace


# Sources:
#