#! /bin/bash

# 00_how_to_docker - 29
# Q: Afficher l’ensemble des tâches du service 'marines'.

SERVICE="marines"

set -o errexit

if [ "$#" -gt 0 ]; then
	echo Usage: "${0}"
	exit 1
fi

set -o xtrace
docker service ps $SERVICE

# Sources:
# docker service ps --help