#! /bin/bash

# 00_how_to_docker - 31
# Q: Forcer l’arrêt et supprimer l’ensemble des services sur le swarm local,
#    en une seule commande

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; docker service ls)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker service rm $(docker service ls -q)

# Sources:
# docker service --help
# docker service ls --help