#! /bin/bash

# 00_how_to_docker - 32
# Q: Forcer l’arrêt et supprimer l’ensemble des containers (tous états confondus),
#    en une seule commande.

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; docker ps -a)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

set -o xtrace
docker rm --force $(docker ps -a -q)

# Sources:
# docker rm --help
# Delete all containers : 	`docker rm $(docker ps -a -q)`