#! /bin/bash

# 00_how_to_docker - 32
# Q: Forcer l’arrêt et supprimer l’ensemble des containers (tous états confondus),
#    en une seule commande.

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; docker ps -a)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

echo "docker rmi --force \$(docker images -q)"
echo
echo "fox_ginger (part 01_dockerfiles) is working and its init is veryyyy long"
read -p "Do you really want to stop and remove every containers ? (Please type 'yesIdo' to confirm) ? "
if [ "$REPLY" = "yesIdo" ]; then
	(set -x; docker rm --force $(docker ps -a -q))
else
	echo "Fiouuuuu :)"
fi

# Sources:
# docker rm --help
# Delete all containers : 	`docker rm $(docker ps -a -q)`