#! /bin/bash

# 00_how_to_docker - 33
# Q: Supprimer l’ensemble des images de containers stocké sur la machine virtuelle
#    'Char', en une seule commande aussi.

set -o errexit

if [ "$#" -gt 0 ]; then
	if [ "${1}" = "-c" ] || [ "${1}" = "--check" ]; then
		(set -x; docker images --all)
	else
		echo Usage: "${0} [OPTION]"
		echo "-c   --check"
	fi
	exit 1
fi

echo "docker rmi --force \$(docker images -q)"
echo
echo "Some images have been build for the part 01_dockerfiles."
read -p "Do you really want to remove every images ? (Please type 'yesIdo' to confirm) ? "
if [ "$REPLY" = "yesIdo" ]; then
	(set -x; docker rmi --force $(docker images -q))
else
	echo "Fiouuuuu :)"
fi

# Sources:
# docker rmi --help
# Delete all images : 		`docker rmi $(docker images -q)`